# Generated by Django 5.0.6 on 2024-06-19 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 18, 8, 41, 706562, tzinfo=datetime.timezone.utc)),
        ),
    ]
