# Generated by Django 5.0.6 on 2024-06-15 14:58

import django.db.models.deletion
import idea_incubator.utils.upload_path
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "cover_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=idea_incubator.utils.upload_path.post_img_upload_path,
                    ),
                ),
                ("description", models.TextField()),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_owner",
                        to="accounts.profile",
                    ),
                ),
            ],
        ),
    ]
