# Generated by Django 5.0.6 on 2024-06-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skill',
            field=models.ManyToManyField(related_name='user_skill', to='core.skill'),
        ),
    ]
