# Generated by Django 5.0.6 on 2024-06-15 14:58

import django.db.models.deletion
import idea_incubator.utils.upload_path
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=idea_incubator.utils.upload_path.profile_picture_upload_path,
                    ),
                ),
                ("about", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
