# Generated by Django 5.0.6 on 2024-06-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_rename_profile_picture_profile_profile_picture_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skills", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="other_skills",
            field=models.CharField(
                blank=True,
                help_text="comma-seperated list of other skills.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.ManyToManyField(
                related_name="user_skills", to="accounts.skills"
            ),
        ),
    ]
