# Generated by Django 5.0.6 on 2024-06-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_skills_profile_other_skills_profile_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
    ]
