# Generated by Django 5.0.6 on 2024-06-16 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_profile_about"),
        ("comments", "0002_alter_comment_post_alter_comment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_comment",
                to="accounts.profile",
            ),
        ),
    ]
