# Generated by Django 5.0.6 on 2024-06-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='skill',
            field=models.ManyToManyField(related_name='post_skill', to='core.skill'),
        ),
    ]
